version: "3"
services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ".:/app"
      working_dir: "/app"
    rabbitmq:
      image: rabbitmq:3.7.7-management-alpine
      ports:
        - "15673:15672"
        - "5673:5672"
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_VHOST: "/dev"